export const mockUsers = [
  {
    id: 1,
    username: 'demo_user',
    firstName: 'Demo',
    lastName: 'User',
    avatar: 'https://i.pravatar.cc/150?u=demo',
    email: 'demo@example.com',
    city: 'San Francisco',
    dob: '1990-01-15',
    bio: 'Passionate developer and tech enthusiast',
    friendsCount: 245,
    phone: '+1-555-0123',
    location: 'San Francisco, CA',
    website: 'https://example.com',
    workplace: 'Tech Corp',
    position: 'Senior Developer',
    education: 'Computer Science, MIT',
    relationship: 'Single',
    interests: ['Coding', 'Photography', 'Travel', 'Music'],
    isVerified: true,
    coverImage: 'https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 2,
    username: 'alice_johnson',
    firstName: 'Alice',
    lastName: 'Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    email: 'alice@example.com',
    city: 'New York',
    dob: '1992-03-20',
    bio: 'Designer and creative thinker',
    friendsCount: 189,
    mutualFriends: 15,
    location: 'New York, NY',
    isFriend: true,
  },
  {
    id: 3,
    username: 'bob_smith',
    firstName: 'Bob',
    lastName: 'Smith',
    avatar: 'https://i.pravatar.cc/150?img=2',
    email: 'bob@example.com',
    city: 'Los Angeles',
    dob: '1988-07-12',
    bio: 'Entrepreneur and startup founder',
    friendsCount: 567,
    mutualFriends: 8,
    location: 'Los Angeles, CA',
    isFriend: false,
  },
  {
    id: 4,
    username: 'carol_davis',
    firstName: 'Carol',
    lastName: 'Davis',
    avatar: 'https://i.pravatar.cc/150?img=3',
    email: 'carol@example.com',
    city: 'Chicago',
    dob: '1995-11-08',
    bio: 'Coffee lover and remote worker',
    friendsCount: 234,
    mutualFriends: 12,
    location: 'Chicago, IL',
    isFriend: true,
  },
  {
    id: 5,
    username: 'david_lee',
    firstName: 'David',
    lastName: 'Lee',
    avatar: 'https://i.pravatar.cc/150?img=4',
    email: 'david@example.com',
    city: 'Seattle',
    dob: '1991-05-18',
    bio: 'Web developer and open source contributor',
    friendsCount: 421,
    mutualFriends: 20,
    location: 'Seattle, WA',
    isFriend: false,
  },
];

export const mockFriendRequests = [
  {
    id: 1,
    name: 'Emma Wilson',
    avatar: 'https://i.pravatar.cc/150?img=5',
    mutualFriends: 5,
    time: '2 hours ago',
  },
  {
    id: 2,
    name: 'Frank Martinez',
    avatar: 'https://i.pravatar.cc/150?img=6',
    mutualFriends: 3,
    time: '5 hours ago',
  },
  {
    id: 3,
    name: 'Grace Chen',
    avatar: 'https://i.pravatar.cc/150?img=7',
    mutualFriends: 8,
    time: '1 day ago',
  },
];

export const mockFriendSuggestions = [
  {
    id: 6,
    name: 'Henry Brown',
    avatar: 'https://i.pravatar.cc/150?img=8',
    mutualFriends: 12,
    reason: 'Works at Tech Corp',
  },
  {
    id: 7,
    name: 'Isabella Garcia',
    avatar: 'https://i.pravatar.cc/150?img=9',
    mutualFriends: 7,
    reason: 'Lives in San Francisco',
  },
  {
    id: 8,
    name: 'Jack Thompson',
    avatar: 'https://i.pravatar.cc/150?img=10',
    mutualFriends: 15,
    reason: 'Studied at MIT',
  },
];

export const mockAllFriends = [
  {
    id: 2,
    name: 'Alice Johnson',
    avatar: 'https://i.pravatar.cc/150?img=1',
    mutualFriends: 15,
    since: 'Friends since 2020',
  },
  {
    id: 4,
    name: 'Carol Davis',
    avatar: 'https://i.pravatar.cc/150?img=3',
    mutualFriends: 12,
    since: 'Friends since 2021',
  },
  {
    id: 9,
    name: 'Karen White',
    avatar: 'https://i.pravatar.cc/150?img=11',
    mutualFriends: 20,
    since: 'Friends since 2019',
  },
  {
    id: 10,
    name: 'Liam Anderson',
    avatar: 'https://i.pravatar.cc/150?img=12',
    mutualFriends: 8,
    since: 'Friends since 2022',
  },
];

export const mockConversations = [
  {
    id: 'conv-1',
    conversationName: 'Alice Johnson',
    conversationAvatar: 'https://i.pravatar.cc/150?img=1',
    modifiedDate: '2025-01-28T11:20:00Z',
    unread: 2,
    lastMessage: 'See you tomorrow!',
    lastTimestamp: '2025-01-28T11:20:00Z',
  },
  {
    id: 'conv-2',
    conversationName: 'Bob Smith',
    conversationAvatar: 'https://i.pravatar.cc/150?img=2',
    modifiedDate: '2025-01-28T09:15:00Z',
    unread: 0,
    lastMessage: 'Thanks for the help!',
    lastTimestamp: '2025-01-28T09:15:00Z',
  },
  {
    id: 'conv-3',
    conversationName: 'Carol Davis',
    conversationAvatar: 'https://i.pravatar.cc/150?img=3',
    modifiedDate: '2025-01-27T18:30:00Z',
    unread: 1,
    lastMessage: 'Did you see the new update?',
    lastTimestamp: '2025-01-27T18:30:00Z',
  },
  {
    id: 'conv-4',
    conversationName: 'Project Team',
    conversationAvatar: 'https://i.pravatar.cc/150?img=20',
    modifiedDate: '2025-01-27T14:00:00Z',
    unread: 5,
    lastMessage: 'Meeting at 3 PM',
    lastTimestamp: '2025-01-27T14:00:00Z',
  },
];

export const mockMessages = {
  'conv-1': [
    {
      id: 'm-1',
      message: 'Hey! How are you?',
      createdDate: '2025-01-28T10:00:00Z',
      me: false,
      sender: { id: 2, avatar: 'https://i.pravatar.cc/150?img=1' },
    },
    {
      id: 'm-2',
      message: "I'm doing great! Working on a new project.",
      createdDate: '2025-01-28T10:05:00Z',
      me: true,
    },
    {
      id: 'm-3',
      message: 'That sounds exciting! What is it about?',
      createdDate: '2025-01-28T10:10:00Z',
      me: false,
      sender: { id: 2, avatar: 'https://i.pravatar.cc/150?img=1' },
    },
    {
      id: 'm-4',
      message: "It's a new social media platform with React and Material-UI",
      createdDate: '2025-01-28T10:15:00Z',
      me: true,
    },
    {
      id: 'm-5',
      message: 'See you tomorrow!',
      createdDate: '2025-01-28T11:20:00Z',
      me: false,
      sender: { id: 2, avatar: 'https://i.pravatar.cc/150?img=1' },
    },
  ],
  'conv-2': [
    {
      id: 'm-6',
      message: 'Can you help me with the deployment?',
      createdDate: '2025-01-28T09:00:00Z',
      me: false,
      sender: { id: 3, avatar: 'https://i.pravatar.cc/150?img=2' },
    },
    {
      id: 'm-7',
      message: 'Sure! What do you need?',
      createdDate: '2025-01-28T09:05:00Z',
      me: true,
    },
    {
      id: 'm-8',
      message: 'Thanks for the help!',
      createdDate: '2025-01-28T09:15:00Z',
      me: false,
      sender: { id: 3, avatar: 'https://i.pravatar.cc/150?img=2' },
    },
  ],
  'conv-3': [
    {
      id: 'm-9',
      message: 'Did you see the new update?',
      createdDate: '2025-01-27T18:30:00Z',
      me: false,
      sender: { id: 4, avatar: 'https://i.pravatar.cc/150?img=3' },
    },
  ],
  'conv-4': [
    {
      id: 'm-10',
      message: 'Good morning team!',
      createdDate: '2025-01-27T09:00:00Z',
      me: false,
      sender: { id: 5, avatar: 'https://i.pravatar.cc/150?img=4', name: 'David' },
    },
    {
      id: 'm-11',
      message: 'Morning!',
      createdDate: '2025-01-27T09:05:00Z',
      me: true,
    },
    {
      id: 'm-12',
      message: 'Meeting at 3 PM',
      createdDate: '2025-01-27T14:00:00Z',
      me: false,
      sender: { id: 6, avatar: 'https://i.pravatar.cc/150?img=5', name: 'Emma' },
    },
  ],
};

export const mockGroups = [
  {
    id: 1,
    name: 'React Developers',
    avatar: 'https://i.pravatar.cc/300?img=20',
    cover: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'A community for React developers to share knowledge and collaborate',
    privacy: 'public',
    members: 12500,
    createdAt: '2023-01-15',
    category: 'Technology',
    isAdmin: true,
    isMember: true,
    unreadPosts: 5,
    lastActivity: '2 hours ago',
    mutualMembers: 25,
    postsPerDay: 15,
  },
  {
    id: 2,
    name: 'Web Design',
    avatar: 'https://i.pravatar.cc/300?img=21',
    cover: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Share and discuss web design trends, tips, and inspiration',
    privacy: 'public',
    members: 8900,
    createdAt: '2023-03-20',
    category: 'Design',
    isAdmin: false,
    isMember: true,
    unreadPosts: 2,
    lastActivity: '1 day ago',
    mutualMembers: 12,
    postsPerDay: 8,
  },
  {
    id: 3,
    name: 'Tech Enthusiasts',
    avatar: 'https://i.pravatar.cc/300?img=22',
    cover: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    description: 'Everything tech - from gadgets to software',
    privacy: 'private',
    members: 5600,
    createdAt: '2023-05-10',
    category: 'Technology',
    isAdmin: false,
    isMember: true,
    unreadPosts: 0,
    lastActivity: '3 days ago',
    mutualMembers: 8,
    postsPerDay: 12,
  },
];

export const mockSuggestedGroups = [
  {
    id: 4,
    name: 'JavaScript Masters',
    avatar: 'https://i.pravatar.cc/300?img=23',
    members: 15000,
    privacy: 'public',
    category: 'Technology',
    mutualMembers: 30,
    description: 'Advanced JavaScript techniques and best practices',
  },
  {
    id: 5,
    name: 'UI/UX Design Community',
    avatar: 'https://i.pravatar.cc/300?img=24',
    members: 9800,
    privacy: 'public',
    category: 'Design',
    mutualMembers: 18,
    description: 'Designers helping designers create better experiences',
  },
];

export const mockGroupMembers = {
  1: [
    { id: 1, name: 'Demo User', avatar: 'https://i.pravatar.cc/150?u=demo', role: 'Admin' },
    { id: 2, name: 'Alice Johnson', avatar: 'https://i.pravatar.cc/150?img=1', role: 'Moderator' },
    { id: 3, name: 'Bob Smith', avatar: 'https://i.pravatar.cc/150?img=2', role: 'Member' },
    { id: 4, name: 'Carol Davis', avatar: 'https://i.pravatar.cc/150?img=3', role: 'Member' },
    { id: 5, name: 'David Lee', avatar: 'https://i.pravatar.cc/150?img=4', role: 'Member' },
  ],
};

export const mockGroupPosts = {
  1: [
    {
      id: 'gp-1',
      author: { id: 2, name: 'Alice Johnson', avatar: 'https://i.pravatar.cc/150?img=1', role: 'Moderator' },
      content: 'Just released a new tutorial on React Hooks! Check it out and let me know what you think.',
      media: [{ type: 'image', url: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=800' }],
      likes: 156,
      comments: 23,
      shares: 8,
      timestamp: '2 hours ago',
      isLiked: false,
    },
    {
      id: 'gp-2',
      author: { id: 3, name: 'Bob Smith', avatar: 'https://i.pravatar.cc/150?img=2', role: 'Member' },
      content: 'Anyone working with React Server Components? I have some questions about best practices.',
      media: [],
      likes: 42,
      comments: 15,
      shares: 2,
      timestamp: '5 hours ago',
      isLiked: true,
    },
  ],
};

export const mockMarketplaceItems = [
  {
    id: 1,
    title: 'MacBook Pro 16-inch',
    price: 2499,
    location: 'San Francisco, CA',
    image: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'John Doe', avatar: 'https://i.pravatar.cc/150?img=1' },
    category: 'Electronics',
  },
  {
    id: 2,
    title: 'iPhone 15 Pro Max',
    price: 1199,
    location: 'New York, NY',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'Jane Smith', avatar: 'https://i.pravatar.cc/150?img=2' },
    category: 'Electronics',
  },
  {
    id: 3,
    title: 'Vintage Sofa',
    price: 450,
    location: 'Los Angeles, CA',
    image: 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'Mike Johnson', avatar: 'https://i.pravatar.cc/150?img=3' },
    category: 'Furniture',
  },
  {
    id: 4,
    title: 'Mountain Bike',
    price: 800,
    location: 'Seattle, WA',
    image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'Sarah Wilson', avatar: 'https://i.pravatar.cc/150?img=4' },
    category: 'Sports',
  },
  {
    id: 5,
    title: 'Canon EOS R5 Camera',
    price: 3899,
    location: 'Chicago, IL',
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'Tom Brown', avatar: 'https://i.pravatar.cc/150?img=5' },
    category: 'Electronics',
  },
  {
    id: 6,
    title: 'Designer Desk Chair',
    price: 350,
    location: 'Austin, TX',
    image: 'https://images.pexels.com/photos/2762247/pexels-photo-2762247.jpeg?auto=compress&cs=tinysrgb&w=800',
    seller: { name: 'Emily Davis', avatar: 'https://i.pravatar.cc/150?img=6' },
    category: 'Furniture',
  },
];

export const mockPages = [
  {
    id: 1,
    name: 'Tech News Daily',
    category: 'Media & News',
    followers: '1.2M',
    avatar: 'https://i.pravatar.cc/150?img=11',
    verified: true,
    following: true,
  },
  {
    id: 2,
    name: 'Design Inspiration',
    category: 'Art & Design',
    followers: '890K',
    avatar: 'https://i.pravatar.cc/150?img=12',
    verified: true,
    following: false,
  },
  {
    id: 3,
    name: 'Coding Academy',
    category: 'Education',
    followers: '650K',
    avatar: 'https://i.pravatar.cc/150?img=13',
    verified: false,
    following: true,
  },
  {
    id: 4,
    name: 'Travel Adventures',
    category: 'Travel & Tourism',
    followers: '2.1M',
    avatar: 'https://i.pravatar.cc/150?img=14',
    verified: true,
    following: false,
  },
];

export const mockSuggestedPages = [
  {
    id: 5,
    name: 'Startup Hub',
    category: 'Business',
    followers: '450K',
    avatar: 'https://i.pravatar.cc/150?img=15',
    verified: false,
    following: false,
  },
  {
    id: 6,
    name: 'Food & Recipes',
    category: 'Food & Dining',
    followers: '1.5M',
    avatar: 'https://i.pravatar.cc/150?img=16',
    verified: true,
    following: false,
  },
];

export const mockSavedItems = [
  {
    id: 1,
    type: 'article',
    title: '10 Tips for Better React Performance',
    description: 'Learn how to optimize your React applications for better performance',
    image: 'https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?auto=compress&cs=tinysrgb&w=800',
    savedDate: '2 days ago',
    category: 'Development',
  },
  {
    id: 2,
    type: 'video',
    title: 'Modern UI Design Trends 2024',
    description: 'Explore the latest trends in user interface design',
    image: 'https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800',
    savedDate: '1 week ago',
    category: 'Design',
  },
  {
    id: 3,
    type: 'link',
    title: 'CSS Grid Complete Guide',
    description: 'Everything you need to know about CSS Grid layout',
    image: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=800',
    savedDate: '3 days ago',
    category: 'Development',
  },
  {
    id: 4,
    type: 'image',
    title: 'Mountain Landscape Photography',
    description: 'Beautiful mountain landscape at sunset',
    image: 'https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=800',
    savedDate: '5 days ago',
    category: 'Photography',
  },
];

export const mockPhotos = [
  'https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/417074/pexels-photo-417074.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/1287145/pexels-photo-1287145.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/158827/beach-sunset-person-walking-158827.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/1933239/pexels-photo-1933239.jpeg?auto=compress&cs=tinysrgb&w=800',
  'https://images.pexels.com/photos/2113566/pexels-photo-2113566.jpeg?auto=compress&cs=tinysrgb&w=800',
];

export const mockSkills = [
  { name: 'React', level: 90 },
  { name: 'JavaScript', level: 95 },
  { name: 'TypeScript', level: 85 },
  { name: 'Node.js', level: 80 },
  { name: 'CSS/SASS', level: 88 },
  { name: 'Python', level: 75 },
];

export const mockActivities = [
  {
    id: 1,
    type: 'post',
    text: 'Created a new post about React hooks',
    time: '2 hours ago',
    icon: 'article',
  },
  {
    id: 2,
    type: 'friend',
    text: 'Became friends with Alice Johnson',
    time: '5 hours ago',
    icon: 'person_add',
  },
  {
    id: 3,
    type: 'group',
    text: 'Joined React Developers group',
    time: '1 day ago',
    icon: 'group',
  },
  {
    id: 4,
    type: 'like',
    text: 'Liked 5 posts',
    time: '2 days ago',
    icon: 'favorite',
  },
  {
    id: 5,
    type: 'comment',
    text: 'Commented on 3 posts',
    time: '3 days ago',
    icon: 'comment',
  },
];

export const mockProfileStats = {
  views: 1234,
  likes: 567,
  friends: 245,
  photos: 89,
  posts: 156,
};

export const mockSettings = {
  profile: {
    name: 'Demo User',
    email: 'demo@example.com',
    phone: '+1-555-0123',
    bio: 'Passionate developer and tech enthusiast',
    location: 'San Francisco, CA',
    website: 'https://example.com',
    avatar: 'https://i.pravatar.cc/150?u=demo',
  },
  privacy: {
    profileVisibility: 'public',
    showEmail: false,
    showPhone: false,
    allowFriendRequests: true,
    allowMessages: true,
    allowTagging: true,
    searchable: true,
  },
  notifications: {
    emailNotifications: true,
    pushNotifications: true,
    friendRequests: true,
    comments: true,
    likes: true,
    messages: true,
    groupInvites: true,
  },
  security: {
    twoFactorAuth: false,
    loginAlerts: true,
    showActiveStatus: true,
  },
};
